package Model;
// Generated 7/12/2020 11:16:12 PM by Hibernate Tools 4.3.1



/**
 * Almacen generated by hbm2java
 */
public class Almacen  implements java.io.Serializable {


     private Integer idAl;
     private String nombre;

    public Almacen() {
    }

    public Almacen(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getIdAl() {
        return this.idAl;
    }
    
    public void setIdAl(Integer idAl) {
        this.idAl = idAl;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


