package Model;
// Generated 7/12/2020 11:16:12 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer idE;
     private Empresa empresa;
     private String nombre;
     private String apellidos;
     private String sexo;
     private Date fechaContra;
     private String cargo;
     private Set<Revisionalmacen> revisionalmacens = new HashSet<Revisionalmacen>(0);
     private Set<Entrada> entradas = new HashSet<Entrada>(0);

    public Empleado() {
        empresa = new Empresa();
    }

    public Empleado(Empresa empresa, String nombre, String apellidos, String sexo, Date fechaContra, String cargo, Set<Revisionalmacen> revisionalmacens, Set<Entrada> entradas) {
       this.empresa = empresa;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.sexo = sexo;
       this.fechaContra = fechaContra;
       this.cargo = cargo;
       this.revisionalmacens = revisionalmacens;
       this.entradas = entradas;
    }
   
    public Integer getIdE() {
        return this.idE;
    }
    
    public void setIdE(Integer idE) {
        this.idE = idE;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Date getFechaContra() {
        return this.fechaContra;
    }
    
    public void setFechaContra(Date fechaContra) {
        this.fechaContra = fechaContra;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public Set<Revisionalmacen> getRevisionalmacens() {
        return this.revisionalmacens;
    }
    
    public void setRevisionalmacens(Set<Revisionalmacen> revisionalmacens) {
        this.revisionalmacens = revisionalmacens;
    }
    public Set<Entrada> getEntradas() {
        return this.entradas;
    }
    
    public void setEntradas(Set<Entrada> entradas) {
        this.entradas = entradas;
    }




}


