package Model;
// Generated 7/12/2020 11:16:12 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Entrada generated by hbm2java
 */
public class Entrada  implements java.io.Serializable {


     private Integer idEnt;
     private Empleado empleado;
     private Date hora;
     private String operacion;

    public Entrada() {
    empleado = new Empleado();
    }

    public Entrada(Empleado empleado, Date hora, String operacion) {
       this.empleado = empleado;
       this.hora = hora;
       this.operacion = operacion;
    }
   
    public Integer getIdEnt() {
        return this.idEnt;
    }
    
    public void setIdEnt(Integer idEnt) {
        this.idEnt = idEnt;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }
    public String getOperacion() {
        return this.operacion;
    }
    
    public void setOperacion(String operacion) {
        this.operacion = operacion;
    }




}


