package Model;
// Generated 7/12/2020 11:16:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProd;
     private Proveedor proveedor;
     private String nombre;
     private String pesoVol;
     private Double costo;
     private Set<Recibeproducto> recibeproductos = new HashSet<Recibeproducto>(0);

    public Producto() {
        proveedor = new Proveedor();
    }

    public Producto(Proveedor proveedor, String nombre, String pesoVol, Double costo, Set<Recibeproducto> recibeproductos) {
       this.proveedor = proveedor;
       this.nombre = nombre;
       this.pesoVol = pesoVol;
       this.costo = costo;
       this.recibeproductos = recibeproductos;
    }
   
    public Integer getIdProd() {
        return this.idProd;
    }
    
    public void setIdProd(Integer idProd) {
        this.idProd = idProd;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPesoVol() {
        return this.pesoVol;
    }
    
    public void setPesoVol(String pesoVol) {
        this.pesoVol = pesoVol;
    }
    public Double getCosto() {
        return this.costo;
    }
    
    public void setCosto(Double costo) {
        this.costo = costo;
    }
    public Set<Recibeproducto> getRecibeproductos() {
        return this.recibeproductos;
    }
    
    public void setRecibeproductos(Set<Recibeproducto> recibeproductos) {
        this.recibeproductos = recibeproductos;
    }




}


