package Model;
// Generated 7/12/2020 11:16:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer idProv;
     private String empresa;
     private String nombreRes;
     private Long telefono;
     private Set<Producto> productos = new HashSet<Producto>(0);
     private Set<Recibeproducto> recibeproductos = new HashSet<Recibeproducto>(0);

    public Proveedor() {
    }

    public Proveedor(String empresa, String nombreRes, Long telefono, Set<Producto> productos, Set<Recibeproducto> recibeproductos) {
       this.empresa = empresa;
       this.nombreRes = nombreRes;
       this.telefono = telefono;
       this.productos = productos;
       this.recibeproductos = recibeproductos;
    }
   
    public Integer getIdProv() {
        return this.idProv;
    }
    
    public void setIdProv(Integer idProv) {
        this.idProv = idProv;
    }
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }
    public String getNombreRes() {
        return this.nombreRes;
    }
    
    public void setNombreRes(String nombreRes) {
        this.nombreRes = nombreRes;
    }
    public Long getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Long telefono) {
        this.telefono = telefono;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }
    public Set<Recibeproducto> getRecibeproductos() {
        return this.recibeproductos;
    }
    
    public void setRecibeproductos(Set<Recibeproducto> recibeproductos) {
        this.recibeproductos = recibeproductos;
    }




}


